json-converted-to-xml
discoverygarden/basic-solr-config pull request #147
Opened 2017-04-11 13:45 UTC by qadan

2017-04-12 16:02 UTC, adam-vessey commented
Depends on https://github.com/discoverygarden/dgi_gsearch_extensions/pull/3

2017-04-12 19:57 UTC, adam-vessey reviewed
Looks good... couple little simplifications possible, but not necessary.

2017-04-12 19:57 UTC, adam-vessey commented on foxmlToSolr.xslt
> +              <xsl:value-of select="java:ca.discoverygarden.gsearch_extensions.FedoraUtils.getRawDatastreamDissemination($PID, @ID, concat($PROT, '://', $HOST, ':', $PORT, '/fedora'), $FEDORAUSER, $F
The `select` could be moved inline in the variable, couldn't it? Like:
```xsl
<xsl:variable name="json"
  select="java:ca.discoverygarden.gsearch_extensions.FedoraUtils.getRawDatastreamDissemination($PID, @ID, concat($PROT, '://', $HOST, ':', $PORT, '/fedora'), $FEDORAUSER, $FEDORAPASS)"/>
```

2017-04-12 19:57 UTC, adam-vessey commented on foxmlToSolr.xslt
> +              <xsl:value-of select="java:ca.discoverygarden.gsearch_extensions.FedoraUtils.getRawDatastreamDissemination($PID, @ID, concat($PROT, '://', $HOST, ':', $PORT, '/fedora'), $FEDORAUSER, $F
Also... could use the other syntax, if we wanted to inline...:
```xsl
<xsl:when test="[... the current test ...]"
  xmlns:dgi-e="xalan://ca.discoverygarden.gsearch_extensions">
  <xsl:variable name="json" select="dgi-e:FedoraUtils.getRawDatastreamDissemination($PID, @ID, concat($PROT, '://', $HOST, ':', $PORT, '/fedora'), $FEDORAUSER, $FEDORAPASS)"/>
  <xsl:apply-templates select="foxml:datastreamVersion[last()]">
    <xsl:with-param name="content" select="dgi-e:JSONToXML.convertJSONToXML($json)"/>
  </xsl:apply-templates>
</xsl:when>
```
or even:
```xsl
<xsl:when test="[... the current test ...]"
  xmlns:dgi-e="xalan://ca.discoverygarden.gsearch_extensions">
  <xsl:apply-templates select="foxml:datastreamVersion[last()]">
    <xsl:with-param name="content" select="dgi-e:JSONToXML.convertJSONToXML(dgi-e:FedoraUtils.getRawDatastreamDissemination($PID, @ID, concat($PROT, '://', $HOST, ':', $PORT, '/fedora'), $FEDORAUSER, $FEDORAPASS))"/>
  </xsl:apply-templates>
</xsl:when>
```
... shrug?

2017-04-18 18:14 UTC, adam-vessey approved these changes

2017-04-18 18:42 UTC, adam-vessey requested changes
Needs to be updated with https://github.com/discoverygarden/islandora_transforms/pull/7

2017-04-19 12:42 UTC, qadan commented
For the basic solr config, I don't believe we target a specific commit of islandora_transforms, we just specify HEAD, so should be fine for this one?

2017-04-19 12:51 UTC, adam-vessey commented
Looks like a particular commit, to me: ![image](https://puu.sh/vpgf9/84e201bcf8.png)

2017-04-19 13:17 UTC, qadan commented
![screen shot 2017-04-19 at 10 16 26 am](https://cloud.githubusercontent.com/assets/3406327/25181870/4f492d52-24e9-11e7-9274-ff9e9ee23d1c.png)

I think that's just meant to be an informative link. The `.gitmodules` file looks thusly

2017-04-19 13:28 UTC, adam-vessey commented
But:
```
velociraptor:repos adam$ git clone https://github.com/discoverygarden/basic-solr-config asdf
Cloning into 'asdf'...
remote: Counting objects: 1228, done.
remote: Total 1228 (delta 0), reused 0 (delta 0), pack-reused 1228
Receiving objects: 100% (1228/1228), 356.15 KiB | 491.00 KiB/s, done.
Resolving deltas: 100% (670/670), done.
velociraptor:repos adam$ cd asdf
velociraptor:asdf adam$ git submodule status islandora_transforms
-fc07d83f4004c6fa2e2210f390c925bc7adf216c islandora_transforms
```
... I'm not sure where exactly it has this info stored...

2017-04-19 13:37 UTC, adam-vessey commented
Similarly:
```
velociraptor:repos adam$ git clone https://github.com/discoverygarden/basic-solr-config qwer --recursive
Cloning into 'qwer'...
remote: Counting objects: 1228, done.
remote: Total 1228 (delta 0), reused 0 (delta 0), pack-reused 1228
Receiving objects: 100% (1228/1228), 356.15 KiB | 446.00 KiB/s, done.
Resolving deltas: 100% (670/670), done.
Submodule 'islandora_transforms' (https://github.com/discoverygarden/islandora_transforms.git) registered for path 'islandora_transforms'
Cloning into '/Users/adam/repos/qwer/islandora_transforms'...
remote: Counting objects: 998, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 998 (delta 0), reused 0 (delta 0), pack-reused 994
Receiving objects: 100% (998/998), 318.81 KiB | 570.00 KiB/s, done.
Resolving deltas: 100% (545/545), done.
Submodule path 'islandora_transforms': checked out 'fc07d83f4004c6fa2e2210f390c925bc7adf216c'
velociraptor:repos adam$
```

2017-04-19 13:39 UTC, qadan commented
figured it out

submodules is goofy

2017-04-19 14:02 UTC, adam-vessey approved these changes

2017-04-28 18:35 UTC, merged